language: generic
global:
  - CLIVERSION=0.7.2
matrix:
  include:
    - env:
        - BOARD="Seeeduino:samd:seeed_XIAO_m0"
    - env:
        - BOARD="Seeeduino:samd:seeed_wio_terminal"

before_install:
  - wget https://github.com/arduino/arduino-cli/releases/download/0.7.2/arduino-cli_0.7.2_Linux_64bit.tar.gz
  - tar xf arduino-cli_0.7.2_Linux_64bit.tar.gz
  - mkdir -p $HOME/bin
  - mv arduino-cli $HOME/bin/arduino-cli
  - export PATH=$PATH:$HOME/bin
  - arduino-cli core update-index --additional-urls  https://files.seeedstudio.com/arduino/package_seeeduino_boards_index.json
  - |
    if [[ "$BOARD" =~ "Seeeduino:samd:" ]]; then
    arduino-cli core install Seeeduino:samd  --additional-urls  https://files.seeedstudio.com/arduino/package_seeeduino_boards_index.json
    fi
install:
  - mkdir -p $HOME/Arduino/libraries

script: 
  - echo "CI Test"
  - arduino-cli board listall --additional-urls  https://files.seeedstudio.com/arduino/package_seeeduino_boards_index.json
  - COREVER=$(arduino-cli core list | grep Seeeduino | awk '{print $2}')
  - echo $COREVER
  - ls . -lh
  - cd ports/samd/
  - mkdir -p build && cd  build
  - |
    if [ "$BOARD" == "Seeeduino:samd:seeed_XIAO_m0" ]; then
      cmake ../ -DARDUINO_CORE_PATH=$HOME/.arduino15/packages/Seeeduino/hardware/samd/$COREVER -DTOOLCHAIN=$HOME/.arduino15/packages/Seeeduino/tools/arm-none-eabi-gcc/7-2017q4/bin -DBOARD=xiao -DARDUINO_VARIANT=XIAO_m0
    elif [ "$BOARD" == "Seeeduino:samd:seeed_wio_terminal" ]; then
      cmake ../ -DARDUINO_CORE_PATH=$HOME/.arduino15/packages/Seeeduino/hardware/samd/$COREVER -DTOOLCHAIN=$HOME/.arduino15/packages/Seeeduino/tools/arm-none-eabi-gcc/7-2017q4/bin -DBOARD=wio_terminal -DARDUINO_VARIANT=wio_terminal
    fi
  - make
  
notifications:
  webhooks:
    urls:
      - https://www.travisbuddy.com/
    on_success: never
    on_failure: always
